// ===== Windows Software Data =====
const windowsSoftware = [
    {
        id: 1760625566488,
        name: 'Visual Studio Code',
        version: '1.85.0',
        category: 'productivity',
        icon: 'fa-solid fa-code',
        description: 'Free source code editor with built-in support for JavaScript, TypeScript, and Node.js',
        fullDescription: 'Visual Studio Code (VS Code) is a free and open-source code editor developed by Microsoft. It supports multiple programming languages, extensions, and debugging tools. VS Code is known for its lightweight performance, smart code completion (IntelliSense), built-in Git support, and customizable interface. It runs on Windows, macOS, and Linux, making it one of the most popular editors among developers worldwide.',
        size: '88.2 MB',
        downloadLink: 'https://code.visualstudio.com/',
        isModified: false,
        screenshots: ['https://code.visualstudio.com/opengraphimg/opengraph-home.png', 'https://preview.redd.it/thats-how-my-vs-code-looks-for-web-development-v0-crpvcfy73djd1.png?width=640&crop=smart&auto=webp&s=43a8e7a288d1f79b66df8d60acedaaf59bfd4750', 'https://code.visualstudio.com/assets/docs/configure/extensions/extension-marketplace/extensions-popular.png'],
        features: ['Free & Open Source: Completely free and open for customization.', 'Multi-language Support: Works with many languages like Python, JavaScript, C++, HTML, and more.', 'IntelliSense: Smart code completion and suggestions.', 'Built-in Git Integration: Manage version control directly inside the editor.', 'Extensions Marketplace: Thousands of plugins for themes, languages, and tools.', 'Debugging Tools: Built-in debugger for various programming languages.', 'Customizable Interface: Change themes, icons, and layout easily.', 'Cross-platform: Runs on Windows, macOS, and Linux.', 'Terminal Integration: Built-in terminal for quick commands.']
    },
    {
        id: 1760625972079,
        name: ' Chrome Browser',
        version: '120.0.6099',
        category: 'productivity',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Google_Chrome_icon_%282011%29.png',
        description: 'Fast, secure, and free web browser built for the modern web',
        fullDescription: 'Google Chrome is a free, fast, and secure web browser developed by Google. It is designed for simplicity and speed, offering features like synchronization across devices, built-in security, extensions, and automatic updates. Chrome supports modern web technologies, providing users with a smooth browsing experience on Windows, macOS, Linux, Android, and iOS.',
        size: '112.5',
        downloadLink: 'https://www.google.com/aclk?sa=L&ai=DChsSEwiVg-3V-qiQAxXWkVAGHYsEBMkYACICCAEQABoCZGc&ae=2&co=1&ase=2&gclid=CjwKCAjwr8LHBhBKEiwAy47uUgO-ijFGa3XwsHK1ws07tR59W92PHbpyH0TPBBkWf-6q61VFlqQY0xoC_YIQAvD_BwE&cid=CAASJeRonQZWQrwqSFwzVzQxxwQnEQjPXNuYZBVm3s3yoSwx5LtXjzk&cce=2&category=acrcp_v1_71&sig=AOD64_0tp4_hSBV3K1CRhKusMi1DM4Xzyg&q&nis=4&adurl&ved=2ahUKEwjCoOXV-qiQAxUMWkEAHfhcMgsQ0Qx6BAgeEAE',
        isModified: false,
        screenshots: ['https://eshop.macsales.com/blog/wp-content/uploads/2018/09/screenshot_122.png', 'https://developer.chrome.com/static/images/2025_ai-challenge.jpg', 'https://img.utdstc.com/screen/fee/785/fee7859e412b27d8527813ab6d0c3242b78de46b2fc51e97f62672ad6c042f0a:600'],
        features: ['Fast Performance: Quick startup and page loading.', 'Simple Interface: Clean and easy-to-use design.', 'Cross-Device Sync: Sync bookmarks, history, and passwords across devices.', 'Extensions Support: Thousands of add-ons available in the Chrome Web Store.', 'Built-in Security: Protects against malware, phishing, and unsafe sites.', 'Automatic Updates: Keeps the browser secure and up to date.', 'Incognito Mode: Browse privately without saving history or cookies.', 'Multi-platform: Available for Windows, macOS, Linux, Android, and iOS.', 'Integrated Google Services: Direct access to Gmail, Drive, and other Google tools.']
    },
    {
        id: 1760626067691,
        name: ' VLC Media Player',
        version: '3.0.22 RC1',
        category: 'multimedia',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/VLC_Icon.svg/250px-VLC_Icon.svg.png',
        description: 'VLC is a versatile, free, and open-source media player that supports playback of most video and audio formats without the need for additional codecs.',
        fullDescription: 'VLC Media Player, developed by the VideoLAN project, is available on multiple operating systems including Windows, macOS, Linux, iOS, and Android. It features a customizable user interface and supports a wide range of formats such as MKV, MP4, AVI, FLAC, and MP3. Advanced features include AI-powered automatic subtitles, playback speed control, advanced subtitle support, and network streaming capabilities.',
        size: '43.12 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.videolan.org/',
        isModified: false,
        screenshots: ['https://game-experience.it/wp-content/uploads/2019/01/vlc-media-player.jpg', 'https://upload.wikimedia.org/wikipedia/commons/c/c2/VLC_3.0.10_running_on_Linux_and_GNOME_Shell.png', 'https://cdn2.portableapps.com/VLCPortable.png'],
        features: ['Playback of most video and audio formats without the need for additional codecs.', 'AI-powered automatic subtitles support for over 100 languages.', 'Playback speed control, seek, and jump features.', 'Advanced subtitle support, including SSA.', 'Network streaming capabilities with support for multiple protocols.', 'Customizable user interface.']
    },
    {
        id: 1760627710498,
        name: 'Remote Mouse',
        version: '5.202',
        category: 'productivity',
        icon: 'https://play-lh.googleusercontent.com/SdvvARqZs4m4oesKw6maedFDV9ftdFCArqsiRj09lzu8km-hY7U1uGgT03dfUeGgSNM',
        description: 'Remote Mouse turns your mobile device into a wireless remote control, functioning as a mouse, keyboard, and touchpad for your computer.',
        fullDescription: 'Remote Mouse allows you to control your computer using your mobile device. It supports Windows, macOS, and Linux operating systems and operates over a Wi-Fi network. The app features a customizable user interface and supports functionalities like volume control, voice typing, and application control.',
        size: '63.04 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.remotemouse.net/',
        isModified: false,
        screenshots: ['https://fossbytes.com/wp-content/uploads/2015/02/Remote-Mouse-iPhone-iPad-App.jpg', 'https://www.remotemouse.net/public/img/cover-rm.jpg', 'https://s3b.cashify.in/gpro/uploads/2023/01/02022209/How-To-Use-Remote-Mouse-App_3-1024x512.jpg'],
        features: ['Transforms mobile device into a wireless mouse, keyboard, and touchpad.', 'Supports voice typing via speech recognition.', 'Controls volume and changes slides in presentations.', 'Supports multi-touch touchpad.', 'Enables cross-device copy and paste functionality.', 'Supports Windows, macOS, and Linux operating systems.']
    },
    {
        id: 1760677535105,
        name: 'Brave Browser',
        version: '1.83.118',
        category: 'productivity',
        icon: 'https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/brave-browser-icon.png',
        description: 'Brave browser is currently the best, fastest and safest',
        fullDescription: 'Brave Browser is a free, open-source web browser developed by Brave Software. It focuses on privacy, speed, and security by blocking ads and trackers by default. Brave also includes a built-in cryptocurrency wallet and a system that rewards users with Basic Attention Tokens (BAT) for viewing privacy-respecting ads. It’s available on Windows, macOS, Linux, Android, and iOS.',
        size: '28',
        downloadLink: 'https://brave.com/',
        isModified: false,
        screenshots: ['https://iili.io/KvFSXEl.png', 'https://iili.io/KvFSWB4.png', 'https://iili.io/KvFSMQf.png'],
        features: ['Privacy-focused: Blocks ads and trackers by default.', 'Fast Performance: Loads pages faster by removing unnecessary content.', 'Built-in Ad Blocker: No need for extra extensions.', 'Rewards System: Earn Basic Attention Tokens (BAT) for viewing privacy-safe ads.', 'Integrated Crypto Wallet: Manage and store cryptocurrencies directly in the browser.', 'Cross-platform: Available on Windows, macOS, Linux, Android, and iOS.', 'HTTPS Everywhere: Automatically upgrades connections to secure HTTPS.', 'Customizable Settings: Control privacy, appearance, and performance easily.', 'Open Source: Transparent and community-driven development.']
    },
    {
        id: 1760688301831,
        name: 'WinRar',
        version: '5.9.1',
        category: 'utilities',
        icon: 'https://upload.wikimedia.org/wikipedia/fr/thumb/a/aa/WinRAR_logo_big.png/250px-WinRAR_logo_big.png',
        description: 'Modified file compression and decompression program without purchase',
        fullDescription: 'WinRAR is a powerful file archiver utility developed by RARLAB. It allows users to compress, extract, and manage archive files easily. WinRAR supports many formats such as RAR, ZIP, 7Z, TAR, and ISO. It is widely used for reducing file sizes and organizing data efficiently. The program is available for Windows, macOS, and Linux.',
        size: '5.71 MB',
        downloadLink: 'https://www.mediafire.com/file/bqupujn550l8dn4/WinRAR_AIO_5.91-en.rar/file',
        originalDownloadLink: 'https://www.win-rar.com/download.html?&L=0',
        isModified: true,
        screenshots: ['https://www.dignited.com/wp-content/uploads/2022/08/WinRAR_.png', 'https://www.win-rar.com/uploads/pics/open-zip-files-extract-files_08.png', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgoZDj2T37WzE_HWvIIO7sJI1ZlQfeuZzag5A-1E7i-zOowbEiAOLa-IT0mTc258QiSLwPXNje9g96S9oSqkz6_XD3W0b0uJ8bdKLBg3ImnYBxATLgZYPWHOKDeAlzxT6KTIbeL8nDXClnOlr62puxTt5u_hFq9q_dGN8EahSIJDnyANwUR35AhfRWYzi0/s1600/Echo%20Chamber%20(2)%20(1).webp'],
        features: ['Powerful Compression: Reduces file sizes efficiently.', 'Supports Multiple Formats: Works with RAR, ZIP, 7Z, TAR, ISO, and more.', 'Strong Encryption: Uses AES-256-bit encryption to protect data.', 'Easy Extraction: Extract files with one click.', 'Password Protection: Secure archives with passwords.', 'Split Archives: Divide large files into smaller parts for easier sharing.', 'Repair Tool: Fix damaged or corrupted archives.', 'User-friendly Interface: Simple and easy to navigate.', 'Multi-language Support: Available in many languages.']
    }
];

// ===== Android Applications Data =====
const androidApps = [
    {
        id: 1760620848459,
        name: 'MT Manager',
        version: '2.14.5',
        category: 'tools',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Mt_Manager_Logo.png',
        description: 'MT Manager is a powerful Android file manager and APK/code editor that lets users modify, translate, and rebuild Android apps directly on their device combining file management, text editing, and APK reverse-engineering tools in one app.',
        fullDescription: 'MT Manager is a powerful Android app used for file management and APK editing. It allows users to browse, copy, move, and modify files, as well as decompile and recompile APK packages. With root access, it can also manage system files. MT Manager is widely used by developers and advanced users for app modification, translation, and file analysis.',
        size: '22.41 MB',
        downloadLink: 'https://www.mediafire.com/file/6cz3vrmslc87g0x/MT_Manager_2.14.5.rar/file',
        originalDownloadLink: 'https://www.mediafire.com/file/j1n11da8u310wyk/mt-manager-2-19-2-orgenal.rar/file',
        isModified: true,
        screenshots: ['https://www.mtmanagerapks.com/wp-content/uploads/2024/07/mt-manager-features.jpg', 'https://images.sftcdn.net/images/t_app-cover-s,f_auto/p/a619d768-3717-4b1b-95df-6990ba44b07a/2318019397/mt-manager-screenshot.png', 'https://i.imgur.com/IdqadjV.png'],
        features: ['File Management: Copy, move, delete, rename files and folders.', 'Dual Window / Split View: View two directories at once to ease file operations.', 'Archive / ZIP Handling: View, extract, compress files in ZIP, RAR, TAR, 7z, etc., and even manipulate contents inside archives without full extraction.', 'Text Editor: Full-featured editor supporting search, replace, syntax, etc.', 'XML, DEX, ARSC Editing: Decompile, edit, and recompile XML, DEX, ARSC files in APKs.', 'LatestModAPKs', 'APK Operations: Sign APKs, clone apps, optimize, remove signature verification, resource obfuscation, translation support.', 'Script Executor: Execute custom scripts (system or extension environment)', 'Hex Editor / Binary Editing: Edit files at the binary (hex) level.', 'Font & SVG Viewing/Editing: Preview fonts, work with SVG, 9-patch graphics, etc.', 'Batch Operations: Select multiple files for mass operations like delete, move, rename.', 'Search & Filter: Find inside XML, search by ID, filter results, etc.', 'Root Access Support: If device is rooted, can access system directories, remount file systems, change permissions.', 'Cloud Integration & FTP: Some versions or plugins may support cloud storage or FTP connection.']
    },
    {
        id: 1760627051300,
        name: 'SSVid',
        version: '1.4.0',
        category: 'general',
        icon: 'https://play-lh.googleusercontent.com/StTPXVol1bhGB96HxBqfoXy7B40r4bl1-4J-Z6LiJ18eGA8JYb7GXCRKs2ywwewVhnbLiDQERYF0SfstvGnn=w600-h300-pc0xffffff-pd',
        description: 'SSVid is a free Android application that allows users to search, stream, and download videos and audio from various platforms such as YouTube and Facebook.',
        fullDescription: 'SSVid is an all-in-one media downloader for Android devices. It enables users to search for content, stream it instantly, or download it for offline enjoyment. The app supports multiple quality options for streaming and downloading, offers background playback support, and allows users to create and manage playlists. It provides a clean, ad-free experience, making it an excellent choice for media enthusiasts.',
        size: '28.17 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.mediafire.com/file/rhl3d8hxlce1i4e/SSVID_1.4.0.apks/file',
        isModified: false,
        screenshots: ['https://image.winudf.com/v2/image1/Y29tLmFsbHZpZGVvZG93bmxvYWRlci51Y2Rvd25sb2FkZXJfc2NyZWVuXzBfMTY2MTU4MzQ3Ml8wOTY/screen-0.jpg?fakeurl=1&type=.jpg', 'https://play-lh.googleusercontent.com/6AgmhIONW2oII1hhgiQGZlL0-OtarEFU7-qn6_i8wX9GyEn9RiSXZVjzUVFRbdLZvA=w526-h296-rw', 'https://www.techuseful.com/wp-content/uploads/2020/12/Allvideodownloader.jpg'],
        features: ['Fast and reliable media search', 'Stream videos in multiple quality options', 'Download videos and audio in various formats', 'Background playback support', 'Create and manage playlists', 'Clean, ad-free experience']
    },
    {
        id: 1760627555294,
        name: 'Remote Mouse',
        version: '3212',
        category: 'tools',
        icon: 'https://play-lh.googleusercontent.com/SdvvARqZs4m4oesKw6maedFDV9ftdFCArqsiRj09lzu8km-hY7U1uGgT03dfUeGgSNM',
        description: 'Remote Mouse turns your Android device into a wireless mouse, keyboard, and touchpad to control your computer via Wi-Fi or Bluetooth.',
        fullDescription: 'Remote Mouse allows Android users to fully control their computers (Windows, macOS, Linux) remotely. Through its simple interface, users can use their phones as a wireless mouse, keyboard, or touchpad. The app supports multi-touch gestures, media control, and clipboard synchronization between devices. It requires the installation of the Remote Mouse server on the target computer to function correctly.',
        size: '53.1 MB',
        downloadLink: 'https://www.mediafire.com/file/61ppihrrzxeev7m/Remote_Mouse_3212.zip/file',
        originalDownloadLink: 'https://www.remotemouse.net/',
        isModified: true,
        screenshots: ['https://fossbytes.com/wp-content/uploads/2015/02/Remote-Mouse-iPhone-iPad-App.jpg', 'https://www.remotemouse.net/public/img/cover-rm.jpg', 'https://www.remotemouse.net/public/img/rm-feature1.png'],
        features: ['Transforms your phone into a wireless mouse, keyboard, and touchpad.', 'Supports multi-touch gestures for smooth control.', 'Controls media playback such as play/pause, volume adjustment, and skip forward/backward.', 'Allows shutting down, restarting, or putting the computer to sleep remotely.', 'Enables clipboard synchronization between phone and computer.', 'User-friendly and intuitive interface.']
    },
    {
        id: 1760628063597,
        name: 'Hail Freezedom',
        version: '1.9.0',
        category: 'tools',
        icon: 'https://f-droid.org/repo/com.aistra.hail/en-US/icon_u7CvMjol4AxutWwPnkgLTgF6bDaYPwlp576Xa283b0M=.png',
        description: 'Hail is a free open-source Android app that lets you freeze (disable, hide, or suspend) other apps when not in use, helping reduce RAM usage and save battery.\nworks on root and Shizuku.',
        fullDescription: 'Hail is a tool for Android that allows users to “freeze” apps—that is, disable, hide, or suspend them—when they are not needed. By doing so, it helps in reducing memory (RAM) consumption and conserving battery life. The apps that are frozen can be reverted (“unfrozen”) when needed.\n\n“Hiding” means the app will not appear in the launcher or in the installed apps list (but can be unhidden). “Disabling” removes it from the launcher (but can be enabled again). “Suspending” (on supported Android versions) shows the icon in grayscale and prevents background activity, popping up a dialog if the user tries to open it.',
        size: '3.3 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.mediafire.com/file/e7y23htnzsoygf8/Hail_1.8.1.zip/file',
        isModified: false,
        screenshots: ['https://i.ytimg.com/vi/fI0D6c4VNZA/maxresdefault.jpg', 'https://droidwin.com/wp-content/uploads/2024/09/hail-app.jpg', 'https://f-droid.org/repo/com.aistra.hail/en-US/phoneScreenshots/3.png'],
        features: ['Freeze / unfreeze apps (disable, hide, suspend)', 'GrapheneOS Discussion Forum', 'Support for different working modes: Device Owner, Root, Shizuku, Dhizuku', 'Revert changes (unfreeze) easily when needed', 'Hide apps (so they don’t appear in launcher or app list)', 'Suspend apps (icon turns grayscale; background and notifications are blocked) on supported versions', 'Works without root for many features (via Shizuku / Dhizuku)', 'GrapheneOS Discussion Forum', 'Free and open source (GPL-3.0)']
    },
    {
        id: 1760670417792,
        name: ' APK Editor Pro',
        version: '1.6.12',
        category: 'tools',
        icon: 'https://img.utdstc.com/icon/ca3/0e4/ca30e4b2f2d983f2f1b1436d64bca9be55e5b8f2a900b09bdee5e446b34bfd8c:200',
        description: 'APK Editor Pro is an Android tool that enables users to edit and customize APK files on their device — modifying resources, permissions, UI elements, and more.',
        fullDescription: 'APK Editor Pro lets users open APK files or applications installed on their device, make changes to parts such as layouts, images, string resources, manifest settings, and then recompile the APK into a modified version. It supports two modes: a simpler mode for resource replacements, and a full-edit / rebuild mode for deep modifications. It is useful for developers or tech-savvy users who want to tweak apps (e.g. change icons, remove ads, adjust permissions). Care must be taken, as improper edits may break the app; backups are recommended.',
        size: '5.31',
        downloadLink: 'https://www.mediafire.com/file/f1iczua6mblucyv/APK_Editor_Pro.ver.1.6.12.build.70.rar/file',
        originalDownloadLink: 'https://www.mediafire.com/file/2q5gnrts3r00rh9/apk-editor-1-9-0.rar/file',
        isModified: true,
        screenshots: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJjajYbyp3oNnLBQ6Dv6iGWtZV28SzMykaEg&s', 'https://play-lh.googleusercontent.com/3G3dZQUtVxrXony7Lvf54xGI7cwWmwukXNF3emFf1RX-y_PYpwL7wch3lGDzaP_FGoAX=rw-w1200', 'https://img.utdstc.com/screen/855/3a6/8553a68c414ddf4bd2258083746a1a87b036d0dad42b20097fbed922ea52803b:600'],
        features: ['Browse and inspect APK contents (resources, manifest, code)', 'Simple edit mode: replace resources (images, strings, layouts)', 'Full edit / rebuild mode: decompile, modify code/resources, recompile', 'Modify AndroidManifest settings (permissions, activities, etc.)', 'Remove or disable ads embedded in apps', 'Adjust or revoke permissions of apps', 'Customize app UI: change icons, backgrounds, strings', 'Backup original APK before editing and restore if needed', 'Work directly on mobile device without needing a PC for many changes', 'Support for multiple editing approaches (simple vs full)']
    },
    {
        id: 1760670709239,
        name: ' App Cloner VIP',
        version: '2.1.1',
        category: 'tools',
        icon: 'https://media.infosec.exchange/infosec.exchange/media_attachments/files/109/483/691/260/285/976/original/c7166899de75f0e4.png',
        description: 'App Cloner lets you create and install multiple modified copies of Android apps so you can run several accounts, tweak behavior, and protect privacy.',
        fullDescription: 'App Cloner is a tool for Android that creates cloned instances of installed apps. Each clone is an independent install so you can run multiple accounts (for example two WhatsApp or Facebook logins) on the same device. In addition to simple cloning, App Cloner’s premium/VIP options add many modding features: change app name and icon, remove or disable permissions, prevent background auto-start, block analytics/ads, force a fresh data directory, spoof device identifiers, limit network access, and apply UI or behavior tweaks. Premium unlocks extra cloning options, more simultaneous clones, and advanced modifications not available in the free/basic edition. Cloned apps are installed separately and can be removed without affecting the original app.',
        size: '21.3',
        downloadLink: 'https://www.mediafire.com/file/n8o49lrwo38d0gk/App_Cloner_VIP_%255BMod_By_ANON%255D_2.1.1.rar/file',
        originalDownloadLink: 'https://appcloner.app/',
        isModified: true,
        screenshots: ['https://liteapks.com/wp-content/uploads/2022/05/app-cloner.jpeg', 'https://appcloner.applisto.com/web/screenshots30/small/026.png', 'https://play-lh.googleusercontent.com/RjZbsmh22gbDGBsGPqVE16EkOX8h0wVJUm81lsJ79NA8AtSlPbzJv0U8rMH2e7oHmyE=w526-h296-rw'],
        features: ['Create multiple independent clones of any compatible Android app.', 'Rename clones and change their app icons.', 'Toggle or remove app permissions for each clone.', 'Disable auto-start/background services and block background activity.', 'Remove or block analytics and certain ad components (where possible).', 'Limit network access for a clone (offline clones) or control notifications.', 'Spoof or reset identifiers for privacy (where supported).', 'Option to sign or re-sign cloned APKs for installation.', 'Premium/VIP add-ons unlock many additional mod options and increase number of allowed clones.', 'Backup and uninstall clones without affecting original app.', 'Useful for multi-account use, testing, privacy separation, and app customization.']
    },
    {
        id: 1760671090904,
        name: 'ZArchiver Pro',
        version: '1.0.8',
        category: 'tools',
        icon: 'https://appteka.store/get/e2Wp1PQuDKBDXQnr3xx9xFbvp_n8xmKoUUVKra4uCno41GZQ-konjdEB7zxrPUYmMNd5Nn6lB4mKl8BZNr2HRokU-I4=/51b296dd65d989fbd9b5c15b5b86b041c9ae3d49.png',
        description: 'ZArchiver Pro is an advanced Android archive manager that allows you to create, extract, and manage compressed files such as ZIP, RAR, 7Z, and many more directly on your device.',
        fullDescription: 'ZArchiver Pro is a professional and feature-rich file compression and extraction tool for Android. It allows users to create and decompress a wide range of archive formats including ZIP, RAR, 7Z, TAR, ISO, BZIP2, and more. The app offers complete control over archive creation parameters like compression level, password protection, and split volumes. Users can view, edit, and extract files without needing to decompress the entire archive, and can also add, delete, or rename files inside existing archives.\n\nZArchiver Pro supports working with encrypted archives and UTF-8 encoded filenames. It includes advanced file operations (cut, copy, paste, rename, delete), multi-threaded processing for better performance on multicore devices, and integration with file browsers for smooth navigation. The Pro version includes dark theme options, faster performance, and improved stability compared to the free version.\n\nIt’s a popular choice among Android users for managing and handling compressed files without needing a PC.',
        size: '4.84',
        downloadLink: 'https://www.mediafire.com/file/kkxv00vgfg0au2a/ZArchiver_Pro.rar/file',
        isModified: true,
        screenshots: ['https://zarchiverr.pro/wp-content/uploads/2024/12/ZArchiver-Donate-Latest-v1.0.10-for-Android-2025.webp', 'https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2023/11/ZArchiver-7.webp', 'https://www.zarchiver.pro/wp-content/uploads/2021/07/zarchiver-apk.jpg'],
        features: ['Create and extract archives (ZIP, RAR, 7Z, TAR, ISO, etc.)', 'View archive contents without extraction', 'Add or remove files inside existing archives', 'Create password-protected or encrypted archives', 'Support for multithreading and fast compression', 'UTF-8 filename support (for international characters)', 'File operations: copy, move, delete, rename', 'Compress multiple files or folders simultaneously', 'Split large archives into parts (volumes)', 'Dark and light themes', 'Ad-free interface (in Pro version)', 'Optimized for Android 11+ and 64-bit processors']
    },
    {
        id: 1760730254180,
        name: 'NP Manager',
        version: '3.1.25',
        category: 'tools',
        icon: 'https://www.farsroid.com/wp-content/uploads/NP-Manager-Logo.png',
        description: 'NP Manager is a tool on Android that acts as an advanced file manager and APK / code editing assistant, supporting operations on APK, DEX, Smali, JAR files along with general file management.',
        fullDescription: 'NP Manager combines powerful file management and code-level capabilities in one app. It allows users to browse internal and external storage (SD, USB OTG), manage all file types (documents, media, archives, apps), and also perform more advanced operations: decompress/compress archives (ZIP, RAR), recycle bin to restore deleted files, hide/show files, manage installed apps, and preview large files. On the more technical side, it supports APK and DEX/Smali editing: conversion between Dex, JAR, Smali; obfuscation, encryption of strings; APK signing and removing signature verification; resource obfuscation; merging/splitting dex files; editing AXML, ARSC; video/audio transcoding or extraction; PDF operations (merge, split, encrypt, decrypt); and toolbox utilities like encoding (base64, MD5, etc.). Some builds include features like LOG injection, removal of popups, disabling VPN/proxy detection, and UI tweaks.\nBecause of its capabilities, it is often compared with “MT Manager” in terms of power and flexibility.',
        size: '43.3 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.mediafire.com/file/53kwfu3oy13g50e/NP_Manager_3.1.25.rar/file',
        isModified: false,
        screenshots: ['https://www.farsroid.com/wp-content/uploads/NP-Manager-Cover.jpg', 'https://mt-manager.net/wp-content/uploads/2025/03/Np-Manager-1.webp', 'https://media.licdn.com/dms/image/v2/D4D12AQHDldvcBNy1eQ/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1712047272179?e=2147483647&v=beta&t=xetqVlYawDLP2rgf_YkWb_TtvL-HUNPFQyrKnhrSLn0'],
        features: ['Support for many file types: documents, media, archives, apps', 'File browsing on internal, external storage, USB OTG', 'Compress / decompress archives (ZIP, RAR)', 'Recycle Bin for recovering deleted files', 'Show / hide hidden files', 'App management: list/uninstall apps', 'Preview large files or resource files', 'APK / DEX / Smali / JAR editing: convert between formats', 'Obfuscation and encryption (string encryption, resource obfuscation)', 'APK signing, removing signature verification', 'Merge / split DEX files', 'Editing AXML / ARSC resources', 'Video/audio transcoding, extraction of streams', 'PDF operations: merge, split, encrypt, decrypt, extract content', 'Utility toolbox: encoding/decoding (base64, MD5, etc.), LOG injection, popup removal', 'UI tweaks, protocol detections (VPN/proxy), disable popups']
    }
];

// ===== FRP Tools Data =====
const frpTools = [
    {
        id: 1760618652737.6975,
        name: 'Samsung FRP Tool',
        version: '2.8',
        category: 'samsung',
        icon: 'fas fa-mobile-alt',
        description: 'Remove FRP lock from Samsung devices running Android 5-13',
        size: '15.2 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.6548,
        name: 'GSM Flasher ADB',
        version: '1.0.7',
        category: 'universal',
        icon: 'fas fa-tools',
        description: 'Universal FRP bypass tool using ADB commands',
        size: '8.5 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.786,
        name: 'Xiaomi Mi Account',
        version: '3.2.1',
        category: 'xiaomi',
        icon: 'fas fa-unlock',
        description: 'Remove Mi Account lock from Xiaomi devices',
        size: '22.8 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.5151,
        name: 'FRP Bypass APK',
        version: '2024.1',
        category: 'universal',
        icon: 'fas fa-key',
        description: 'Android app to bypass Google account verification',
        size: '4.2 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.3093,
        name: 'Oppo FRP Unlock',
        version: '1.5.8',
        category: 'oppo',
        icon: 'fas fa-lock-open',
        description: 'Professional tool for Oppo and Realme FRP removal',
        size: '18.6 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.0286,
        name: 'Samsung Odin',
        version: '3.14.4',
        category: 'samsung',
        icon: 'fas fa-sync',
        description: 'Official Samsung flashing tool for firmware and FRP',
        size: '5.8 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.0454,
        name: 'MiFlash Unlock',
        version: '6.5.224',
        category: 'xiaomi',
        icon: 'fas fa-mobile',
        description: 'Official Xiaomi bootloader unlock tool',
        size: '62.4 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.2207,
        name: 'Realme Flash Tool',
        version: '2.0.1',
        category: 'oppo',
        icon: 'fas fa-download',
        description: 'Flash firmware and remove FRP on Realme devices',
        size: '45.2 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.3555,
        name: 'FRP Hijacker',
        version: '1.0',
        category: 'universal',
        icon: 'fas fa-user-secret',
        description: 'Advanced FRP bypass tool for multiple brands',
        size: '12.4 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.1685,
        name: 'Samsung ENG Boot',
        version: '2023.12',
        category: 'samsung',
        icon: 'fas fa-cog',
        description: 'Engineering boot files for Samsung FRP bypass',
        size: '285 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.3015,
        name: 'Xiaomi EDL Auth',
        version: '2.1',
        category: 'xiaomi',
        icon: 'fas fa-shield-alt',
        description: 'EDL authentication bypass for Xiaomi devices',
        size: '8.9 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.6748,
        name: 'Universal ADB',
        version: '5.0',
        category: 'universal',
        icon: 'fas fa-terminal',
        description: 'ADB drivers and FRP tools for all Android devices',
        size: '32.5 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.4075,
        name: 'Oppo A3s Tool',
        version: '1.2',
        category: 'oppo',
        icon: 'fas fa-wrench',
        description: 'Specialized tool for Oppo A3s FRP and pattern unlock',
        size: '14.8 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.385,
        name: 'Samsung Combination',
        version: '2024',
        category: 'samsung',
        icon: 'fas fa-file-archive',
        description: 'Combination firmware files for Samsung FRP bypass',
        size: '1.2 GB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.4863,
        name: 'Technocare APK',
        version: '8.0.1',
        category: 'universal',
        icon: 'fas fa-magic',
        description: 'One-click FRP bypass APK for Android 5-8',
        size: '2.8 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737,
        name: 'Samsung FRP Tool',
        version: '2.8',
        category: 'samsung',
        icon: 'fas fa-mobile-alt',
        description: 'Remove FRP lock from Samsung devices running Android 5-13',
        size: '15.2 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.google.com/?zx=1760730654315&no_sw_cr=1',
        isModified: false
    }
];

// ===== FRP Applications Data =====
const frpApps = [
    {
        id: 1760618652737.7964,
        name: 'FRP Bypass APK',
        version: '2024.5',
        category: 'universal',
        icon: 'fas fa-unlock-alt',
        description: 'Universal FRP bypass application for Android 5-14',
        size: '4.8 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.1511,
        name: 'Samsung FRP Helper',
        version: '3.2.1',
        category: 'samsung',
        icon: 'fas fa-mobile-alt',
        description: 'Specialized FRP bypass app for Samsung Galaxy devices',
        size: '6.5 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.634,
        name: 'Quick Shortcut Maker',
        version: '2.4.0',
        category: 'universal',
        icon: 'fas fa-bolt',
        description: 'Create shortcuts to bypass FRP lock screen',
        size: '3.2 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.9023,
        name: 'Xiaomi FRP Unlocker',
        version: '2.0.8',
        category: 'xiaomi',
        icon: 'fas fa-key',
        description: 'Remove Mi Account and FRP from Xiaomi devices',
        size: '8.4 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.8284,
        name: 'Pangu FRP Bypass',
        version: '1.8.2',
        category: 'universal',
        icon: 'fas fa-shield-alt',
        description: 'Advanced FRP removal tool for multiple brands',
        size: '5.6 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.4976,
        name: 'Huawei ID Bypass',
        version: '1.5.4',
        category: 'huawei',
        icon: 'fas fa-unlock',
        description: 'Remove Huawei ID and FRP lock',
        size: '7.2 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.6384,
        name: 'Oppo FRP Remover',
        version: '2.3.1',
        category: 'oppo',
        icon: 'fas fa-lock-open',
        description: 'Remove FRP and pattern lock from Oppo devices',
        size: '6.8 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.605,
        name: 'Test DPC',
        version: '7.0.5',
        category: 'universal',
        icon: 'fas fa-vial',
        description: 'Device Policy Controller for FRP bypass',
        size: '4.1 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.7026,
        name: 'Realme FRP Tool',
        version: '1.9.2',
        category: 'realme',
        icon: 'fas fa-mobile',
        description: 'FRP bypass and unlock tool for Realme devices',
        size: '5.9 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.2854,
        name: 'Samsung Bypass 2024',
        version: '4.0.1',
        category: 'samsung',
        icon: 'fas fa-tools',
        description: 'Latest Samsung FRP bypass for Android 14',
        size: '7.8 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.334,
        name: 'Alliance Shield',
        version: '1.0.4',
        category: 'universal',
        icon: 'fas fa-user-shield',
        description: 'Multiple FRP bypass methods in one app',
        size: '9.2 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.4646,
        name: 'Xiaomi Unlocker Pro',
        version: '3.1.5',
        category: 'xiaomi',
        icon: 'fas fa-crown',
        description: 'Professional Mi Account and FRP remover',
        size: '10.5 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.3062,
        name: 'FRP Skip',
        version: '2.2.0',
        category: 'universal',
        icon: 'fas fa-forward',
        description: 'Skip Google account verification on any device',
        size: '3.8 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.81,
        name: 'Huawei FRP Master',
        version: '2.6.3',
        category: 'huawei',
        icon: 'fas fa-graduation-cap',
        description: 'Complete FRP solution for Huawei and Honor',
        size: '8.9 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.9365,
        name: 'Realme Quick Bypass',
        version: '1.4.7',
        category: 'realme',
        icon: 'fas fa-rocket',
        description: 'Fast FRP bypass for all Realme models',
        size: '5.3 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.658,
        name: 'Samsung Knox Bypass',
        version: '1.2.8',
        category: 'samsung',
        icon: 'fas fa-lock',
        description: 'Bypass Samsung Knox and FRP protection',
        size: '11.2 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.808,
        name: 'Oppo ColorOS FRP',
        version: '2.1.4',
        category: 'oppo',
        icon: 'fas fa-palette',
        description: 'FRP bypass for ColorOS 7-13',
        size: '7.6 MB',
        downloadLink: 'undefined',
        isModified: false
    },
    {
        id: 1760618652737.7043,
        name: 'D&G FRP Tool',
        version: '3.5.2',
        category: 'universal',
        icon: 'fas fa-wrench',
        description: 'Professional FRP bypass for Android 8-14',
        size: '6.4 MB',
        downloadLink: 'undefined',
        isModified: false
    }
];