// ===== Windows Software Data =====
const windowsSoftware = [
    {
        id: 1760625566488,
        name: 'Visual Studio Code',
        version: '1.85.0',
        category: 'Programming',
        icon: 'fa-solid fa-code',
        description: 'A free, lightweight, and powerful code editor developed by Microsoft, supporting multiple programming languages and extensions for modern development.',
        fullDescription: 'Visual Studio Code (VS Code) is a free and open-source code editor developed by Microsoft. It supports multiple programming languages, extensions, and debugging tools. VS Code is known for its lightweight performance, smart code completion (IntelliSense), built-in Git support, and customizable interface. It runs on Windows, macOS, and Linux, making it one of the most popular editors among developers worldwide.',
        size: '88.2 MB',
        downloadLink: 'https://code.visualstudio.com/',
        isModified: false,
        screenshots: ['https://code.visualstudio.com/opengraphimg/opengraph-home.png', 'https://preview.redd.it/thats-how-my-vs-code-looks-for-web-development-v0-crpvcfy73djd1.png?width=640&crop=smart&auto=webp&s=43a8e7a288d1f79b66df8d60acedaaf59bfd4750', 'https://code.visualstudio.com/assets/docs/configure/extensions/extension-marketplace/extensions-popular.png'],
        features: ['Free & Open Source: Completely free and open for customization.', 'Multi-language Support: Works with many languages like Python, JavaScript, C++, HTML, and more.', 'IntelliSense: Smart code completion and suggestions.', 'Built-in Git Integration: Manage version control directly inside the editor.', 'Extensions Marketplace: Thousands of plugins for themes, languages, and tools.', 'Debugging Tools: Built-in debugger for various programming languages.', 'Customizable Interface: Change themes, icons, and layout easily.', 'Cross-platform: Runs on Windows, macOS, and Linux.', 'Terminal Integration: Built-in terminal for quick commands.']
    },
    {
        id: 1760625972079,
        name: ' Chrome Browser',
        version: '120.0.6099',
        category: 'Browser',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Google_Chrome_icon_%282011%29.png',
        description: 'A fast, secure, and intelligent web browser by Google, offering seamless browsing, syncing, and advanced privacy protection across devices.',
        fullDescription: 'Google Chrome is a free, fast, and secure web browser developed by Google. It is designed for simplicity and speed, offering features like synchronization across devices, built-in security, extensions, and automatic updates. Chrome supports modern web technologies, providing users with a smooth browsing experience on Windows, macOS, Linux, Android, and iOS.',
        size: '112.5',
        downloadLink: 'https://www.google.com/aclk?sa=L&ai=DChsSEwiVg-3V-qiQAxXWkVAGHYsEBMkYACICCAEQABoCZGc&ae=2&co=1&ase=2&gclid=CjwKCAjwr8LHBhBKEiwAy47uUgO-ijFGa3XwsHK1ws07tR59W92PHbpyH0TPBBkWf-6q61VFlqQY0xoC_YIQAvD_BwE&cid=CAASJeRonQZWQrwqSFwzVzQxxwQnEQjPXNuYZBVm3s3yoSwx5LtXjzk&cce=2&category=acrcp_v1_71&sig=AOD64_0tp4_hSBV3K1CRhKusMi1DM4Xzyg&q&nis=4&adurl&ved=2ahUKEwjCoOXV-qiQAxUMWkEAHfhcMgsQ0Qx6BAgeEAE',
        isModified: false,
        screenshots: ['https://eshop.macsales.com/blog/wp-content/uploads/2018/09/screenshot_122.png', 'https://developer.chrome.com/static/images/2025_ai-challenge.jpg', 'https://img.utdstc.com/screen/fee/785/fee7859e412b27d8527813ab6d0c3242b78de46b2fc51e97f62672ad6c042f0a:600'],
        features: ['Fast Performance: Quick startup and page loading.', 'Simple Interface: Clean and easy-to-use design.', 'Cross-Device Sync: Sync bookmarks, history, and passwords across devices.', 'Extensions Support: Thousands of add-ons available in the Chrome Web Store.', 'Built-in Security: Protects against malware, phishing, and unsafe sites.', 'Automatic Updates: Keeps the browser secure and up to date.', 'Incognito Mode: Browse privately without saving history or cookies.', 'Multi-platform: Available for Windows, macOS, Linux, Android, and iOS.', 'Integrated Google Services: Direct access to Gmail, Drive, and other Google tools.']
    },
    {
        id: 1760626067691,
        name: ' VLC Media Player',
        version: '3.0.22 RC1',
        category: 'Multiplayer',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/VLC_Icon.svg/250px-VLC_Icon.svg.png',
        description: 'VLC is a versatile, free, and open-source media player that supports playback of most video and audio formats without the need for additional codecs.',
        fullDescription: 'VLC Media Player, developed by the VideoLAN project, is available on multiple operating systems including Windows, macOS, Linux, iOS, and Android. It features a customizable user interface and supports a wide range of formats such as MKV, MP4, AVI, FLAC, and MP3. Advanced features include AI-powered automatic subtitles, playback speed control, advanced subtitle support, and network streaming capabilities.',
        size: '43.12 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.videolan.org/',
        isModified: false,
        screenshots: ['https://game-experience.it/wp-content/uploads/2019/01/vlc-media-player.jpg', 'https://upload.wikimedia.org/wikipedia/commons/c/c2/VLC_3.0.10_running_on_Linux_and_GNOME_Shell.png', 'https://cdn2.portableapps.com/VLCPortable.png'],
        features: ['Playback of most video and audio formats without the need for additional codecs.', 'AI-powered automatic subtitles support for over 100 languages.', 'Playback speed control, seek, and jump features.', 'Advanced subtitle support, including SSA.', 'Network streaming capabilities with support for multiple protocols.', 'Customizable user interface.']
    },
    {
        id: 1760627710498,
        name: 'Remote Mouse',
        version: '5.202',
        category: 'Utilities',
        icon: 'https://play-lh.googleusercontent.com/SdvvARqZs4m4oesKw6maedFDV9ftdFCArqsiRj09lzu8km-hY7U1uGgT03dfUeGgSNM',
        description: 'Remote Mouse turns your mobile device into a wireless remote control, functioning as a mouse, keyboard, and touchpad for your computer.',
        fullDescription: 'Remote Mouse allows you to control your computer using your mobile device. It supports Windows, macOS, and Linux operating systems and operates over a Wi-Fi network. The app features a customizable user interface and supports functionalities like volume control, voice typing, and application control.',
        size: '63.04 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.remotemouse.net/',
        isModified: false,
        screenshots: ['https://fossbytes.com/wp-content/uploads/2015/02/Remote-Mouse-iPhone-iPad-App.jpg', 'https://www.remotemouse.net/public/img/cover-rm.jpg', 'https://s3b.cashify.in/gpro/uploads/2023/01/02022209/How-To-Use-Remote-Mouse-App_3-1024x512.jpg'],
        features: ['Transforms mobile device into a wireless mouse, keyboard, and touchpad.', 'Supports voice typing via speech recognition.', 'Controls volume and changes slides in presentations.', 'Supports multi-touch touchpad.', 'Enables cross-device copy and paste functionality.', 'Supports Windows, macOS, and Linux operating systems.']
    },
    {
        id: 1760677535105,
        name: 'Brave Browser',
        version: '1.83.118',
        category: 'Browser',
        icon: 'https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/brave-browser-icon.png',
        description: 'A fast, private, and secure web browser that blocks ads and trackers by default, providing a safer and faster browsing experience.',
        fullDescription: 'Brave Browser is a free, open-source web browser developed by Brave Software. It focuses on privacy, speed, and security by blocking ads and trackers by default. Brave also includes a built-in cryptocurrency wallet and a system that rewards users with Basic Attention Tokens (BAT) for viewing privacy-respecting ads. It’s available on Windows, macOS, Linux, Android, and iOS.',
        size: '28',
        downloadLink: 'https://brave.com/',
        isModified: false,
        screenshots: ['https://iili.io/KvFSXEl.png', 'https://iili.io/KvFSWB4.png', 'https://iili.io/KvFSMQf.png'],
        features: ['Privacy-focused: Blocks ads and trackers by default.', 'Fast Performance: Loads pages faster by removing unnecessary content.', 'Built-in Ad Blocker: No need for extra extensions.', 'Rewards System: Earn Basic Attention Tokens (BAT) for viewing privacy-safe ads.', 'Integrated Crypto Wallet: Manage and store cryptocurrencies directly in the browser.', 'Cross-platform: Available on Windows, macOS, Linux, Android, and iOS.', 'HTTPS Everywhere: Automatically upgrades connections to secure HTTPS.', 'Customizable Settings: Control privacy, appearance, and performance easily.', 'Open Source: Transparent and community-driven development.']
    },
    {
        id: 1760688301831,
        name: 'WinRar',
        version: '5.9.1',
        category: 'Utilities',
        icon: 'https://upload.wikimedia.org/wikipedia/fr/thumb/a/aa/WinRAR_logo_big.png/250px-WinRAR_logo_big.png',
        description: 'A powerful file compression and archiving tool that allows users to create, extract, and manage compressed files in multiple formats.',
        fullDescription: 'WinRAR is a powerful file archiver utility developed by RARLAB. It allows users to compress, extract, and manage archive files easily. WinRAR supports many formats such as RAR, ZIP, 7Z, TAR, and ISO. It is widely used for reducing file sizes and organizing data efficiently. The program is available for Windows, macOS, and Linux.',
        size: '5.71 MB',
        downloadLink: 'https://www.mediafire.com/file/bqupujn550l8dn4/WinRAR_AIO_5.91-en.rar/file',
        originalDownloadLink: 'https://www.win-rar.com/download.html?&L=0',
        isModified: true,
        screenshots: ['https://www.dignited.com/wp-content/uploads/2022/08/WinRAR_.png', 'https://www.win-rar.com/uploads/pics/open-zip-files-extract-files_08.png', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgoZDj2T37WzE_HWvIIO7sJI1ZlQfeuZzag5A-1E7i-zOowbEiAOLa-IT0mTc258QiSLwPXNje9g96S9oSqkz6_XD3W0b0uJ8bdKLBg3ImnYBxATLgZYPWHOKDeAlzxT6KTIbeL8nDXClnOlr62puxTt5u_hFq9q_dGN8EahSIJDnyANwUR35AhfRWYzi0/s1600/Echo%20Chamber%20(2)%20(1).webp'],
        features: ['Powerful Compression: Reduces file sizes efficiently.', 'Supports Multiple Formats: Works with RAR, ZIP, 7Z, TAR, ISO, and more.', 'Strong Encryption: Uses AES-256-bit encryption to protect data.', 'Easy Extraction: Extract files with one click.', 'Password Protection: Secure archives with passwords.', 'Split Archives: Divide large files into smaller parts for easier sharing.', 'Repair Tool: Fix damaged or corrupted archives.', 'User-friendly Interface: Simple and easy to navigate.', 'Multi-language Support: Available in many languages.']
    },
    {
        id: 1760780124868,
        name: 'FastStone Capture',
        version: '10.9',
        category: 'general',
        icon: 'https://iili.io/KvtMa0Q.png',
        description: 'A lightweight and powerful screen capture and video recording tool for Windows that lets you easily capture, annotate, and share anything on your screen.',
        fullDescription: 'FastStone Capture is a full-featured screenshot and screen-recording application for Windows that enables you to capture nearly everything you see on the screen — whether it’s a window, a menu, a full screen, a freehand region or a fixed region, even a scrolling web page or window. It also supports screen recording of activities (including mouse movements, clicks, audio from microphone, webcam in newer versions) into a video file. After capture you can send outputs to editor, clipboard, file, printer, e-mail, Word/PowerPoint document or upload to website. It includes a built-in image editor that lets you annotate (text, arrows, highlights, watermarks, shapes), apply effects (drop shadow, torn edge, fade edge), resize, crop, rotate, sharpen, adjust colours and more. It supports saving images in multiple formats (BMP, GIF, JPEG, PCX, PNG, TGA, TIFF, PDF) and videos in WMV format (and possibly MP4 in latest versions) and comes with global hotkeys, automatic file name generation, support for external editors, colour-picker, screen magnifier, screen ruler and other tools',
        size: '8.49 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.mediafire.com/file/ed3wps0320yr2uu/FastStone+Capture+v10.9.rar/file',
        isModified: false,
        screenshots: ['https://faststone-capture.fileion.com/curator/software/articles/featued-images/2025/08/faststone-capture-keyboard-shortcuts.webp?s=b3f309af83b4cfa8662ffb0fca48439a', 'https://blackjoomla.com/media/k2/items/cache/05a977f75c8bd421cf67e35678973f79_XL.jpg', 'https://faststone-capture.fileion.com/storage/software/screenshots/2025/07/faststone-capture-1.png'],
        features: ['Capture full screen, active window, object, menu, rectangular/freehand/fixed region, scrolling windows/web pages.', 'Record screen activities including on-screen changes, microphone audio, mouse movements/clicks and webcam (in recent versions).', 'Built-in editor: annotate images with text, arrowed lines, highlights, watermarks, shapes; apply effects (drop shadow, torn-edge, fade-edge).', 'Resize, crop, rotate, sharpen images; adjust brightness, colour, etc.', 'Save images in many formats (BMP, GIF, JPEG, PCX, PNG, TGA, TIFF, PDF).', 'Built-in video editor allowing trimming, zoom effects, convert video to animated GIF (some versions) …', 'Support for global hotkeys, automatic filename generation, external editor integration, colour picker, screen magnifier, screen crosshair, screen ruler.', 'Lightweight, fast, efficient in system resources.']
    },
    {
        id: 1760780470022,
        name: 'IObit Driver Booster Silent',
        version: '8.3',
        category: 'Driver',
        icon: 'https://images-eds-ssl.xboxlive.com/image?url=4rt9.lXDC4H_93laV1_eHM0OYfiFeMI2p9MWie0CvL99U4GA1gf6_kayTt_kBblFwHwo8BW8JXlqfnYxKPmmBR_lQTW0utfoTf1PCUV5Nj40Jn2ThHcxw5xDAwd6lbjK62aWliqpTTqG0qoBQHnTpPnFxjf3.9b74rW6xhvE7eA-&format=source',
        description: 'A professional tool to scan, update, and manage outdated or missing drivers on Windows silently without user intervention.',
        fullDescription: 'IObit Driver Booster Silent is an advanced driver updating utility that helps keep your system stable and optimized. It automatically scans your PC for outdated, missing, or faulty drivers and updates them with one click. The “Silent” version performs all actions quietly in the background without showing notifications or requiring confirmation, making it ideal for technicians or users who prefer a fully automated process. It also helps improve gaming performance, fix system crashes, and ensure hardware compatibility.',
        size: '28.8 MB',
        downloadLink: 'https://www.mediafire.com/file/vfdbzjb0jpni92f/IObit_Driver_Booster_silent.rar/file',
        originalDownloadLink: 'https://www.iobit.com/en/driver-booster.php',
        isModified: true,
        screenshots: ['https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/920630/capsule_616x353.jpg?t=1759047863', 'https://www.iobit.com/tpl/images/screenshot/db/tools_510.png', 'https://www.iobit.com/tpl/images/screenshot/db/scaning_117.png'],
        features: ['Automatic detection and update of outdated drivers', 'Silent installation mode with no user interaction', 'Improved system stability and performance', 'Game-ready driver optimization', 'Backup and restore drivers easily', 'Fixes hardware issues caused by faulty drivers', 'Simple and user-friendly interface', 'Fast download and installation process']
    }
];

// ===== Android Applications Data =====
const androidApps = [
    {
        id: 1760620848459,
        name: 'MT Manager',
        version: '2.14.5',
        category: 'Utilities',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Mt_Manager_Logo.png',
        description: 'A powerful Android file manager and APK editor that allows users to modify, translate, and manage applications directly on their devices.',
        fullDescription: 'MT Manager is a powerful Android app used for file management and APK editing. It allows users to browse, copy, move, and modify files, as well as decompile and recompile APK packages. With root access, it can also manage system files. MT Manager is widely used by developers and advanced users for app modification, translation, and file analysis.',
        size: '22.41 MB',
        downloadLink: 'https://www.mediafire.com/file/6cz3vrmslc87g0x/MT_Manager_2.14.5.rar/file',
        originalDownloadLink: 'https://www.mediafire.com/file/j1n11da8u310wyk/mt-manager-2-19-2-orgenal.rar/file',
        isModified: true,
        screenshots: ['https://www.mtmanagerapks.com/wp-content/uploads/2024/07/mt-manager-features.jpg', 'https://images.sftcdn.net/images/t_app-cover-s,f_auto/p/a619d768-3717-4b1b-95df-6990ba44b07a/2318019397/mt-manager-screenshot.png', 'https://i.imgur.com/IdqadjV.png'],
        features: ['File Management: Copy, move, delete, rename files and folders.', 'Dual Window / Split View: View two directories at once to ease file operations.', 'Archive / ZIP Handling: View, extract, compress files in ZIP, RAR, TAR, 7z, etc., and even manipulate contents inside archives without full extraction.', 'Text Editor: Full-featured editor supporting search, replace, syntax, etc.', 'XML, DEX, ARSC Editing: Decompile, edit, and recompile XML, DEX, ARSC files in APKs.', 'LatestModAPKs', 'APK Operations: Sign APKs, clone apps, optimize, remove signature verification, resource obfuscation, translation support.', 'Script Executor: Execute custom scripts (system or extension environment)', 'Hex Editor / Binary Editing: Edit files at the binary (hex) level.', 'Font & SVG Viewing/Editing: Preview fonts, work with SVG, 9-patch graphics, etc.', 'Batch Operations: Select multiple files for mass operations like delete, move, rename.', 'Search & Filter: Find inside XML, search by ID, filter results, etc.', 'Root Access Support: If device is rooted, can access system directories, remount file systems, change permissions.', 'Cloud Integration & FTP: Some versions or plugins may support cloud storage or FTP connection.']
    },
    {
        id: 1760627051300,
        name: 'SSVid',
        version: '1.4.0',
        category: 'Download App',
        icon: 'https://play-lh.googleusercontent.com/StTPXVol1bhGB96HxBqfoXy7B40r4bl1-4J-Z6LiJ18eGA8JYb7GXCRKs2ywwewVhnbLiDQERYF0SfstvGnn=w600-h300-pc0xffffff-pd',
        description: 'SSVid is a free Android application that allows users to search, stream, and download videos and audio from various platforms such as YouTube and Facebook.',
        fullDescription: 'SSVid is an all-in-one media downloader for Android devices. It enables users to search for content, stream it instantly, or download it for offline enjoyment. The app supports multiple quality options for streaming and downloading, offers background playback support, and allows users to create and manage playlists. It provides a clean, ad-free experience, making it an excellent choice for media enthusiasts.',
        size: '28.17 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.mediafire.com/file/rhl3d8hxlce1i4e/SSVID_1.4.0.apks/file',
        isModified: false,
        screenshots: ['https://image.winudf.com/v2/image1/Y29tLmFsbHZpZGVvZG93bmxvYWRlci51Y2Rvd25sb2FkZXJfc2NyZWVuXzBfMTY2MTU4MzQ3Ml8wOTY/screen-0.jpg?fakeurl=1&type=.jpg', 'https://play-lh.googleusercontent.com/6AgmhIONW2oII1hhgiQGZlL0-OtarEFU7-qn6_i8wX9GyEn9RiSXZVjzUVFRbdLZvA=w526-h296-rw', 'https://www.techuseful.com/wp-content/uploads/2020/12/Allvideodownloader.jpg'],
        features: ['Fast and reliable media search', 'Stream videos in multiple quality options', 'Download videos and audio in various formats', 'Background playback support', 'Create and manage playlists', 'Clean, ad-free experience']
    },
    {
        id: 1760627555294,
        name: 'Remote Mouse',
        version: '3212',
        category: 'Utilities',
        icon: 'https://play-lh.googleusercontent.com/SdvvARqZs4m4oesKw6maedFDV9ftdFCArqsiRj09lzu8km-hY7U1uGgT03dfUeGgSNM',
        description: 'Remote Mouse turns your Android device into a wireless mouse, keyboard, and touchpad to control your computer via Wi-Fi or Bluetooth.',
        fullDescription: 'Remote Mouse allows Android users to fully control their computers (Windows, macOS, Linux) remotely. Through its simple interface, users can use their phones as a wireless mouse, keyboard, or touchpad. The app supports multi-touch gestures, media control, and clipboard synchronization between devices. It requires the installation of the Remote Mouse server on the target computer to function correctly.',
        size: '53.1 MB',
        downloadLink: 'https://www.mediafire.com/file/61ppihrrzxeev7m/Remote_Mouse_3212.zip/file',
        originalDownloadLink: 'https://www.remotemouse.net/',
        isModified: true,
        screenshots: ['https://fossbytes.com/wp-content/uploads/2015/02/Remote-Mouse-iPhone-iPad-App.jpg', 'https://www.remotemouse.net/public/img/cover-rm.jpg', 'https://www.remotemouse.net/public/img/rm-feature1.png'],
        features: ['Transforms your phone into a wireless mouse, keyboard, and touchpad.', 'Supports multi-touch gestures for smooth control.', 'Controls media playback such as play/pause, volume adjustment, and skip forward/backward.', 'Allows shutting down, restarting, or putting the computer to sleep remotely.', 'Enables clipboard synchronization between phone and computer.', 'User-friendly and intuitive interface.']
    },
    {
        id: 1760628063597,
        name: 'Hail Freezedom',
        version: '1.9.0',
        category: 'Utilities',
        icon: 'https://f-droid.org/repo/com.aistra.hail/en-US/icon_u7CvMjol4AxutWwPnkgLTgF6bDaYPwlp576Xa283b0M=.png',
        description: 'Hail is a free open-source Android app that lets you freeze (disable, hide, or suspend) other apps when not in use, helping reduce RAM usage and save battery.\nworks on root and Shizuku.',
        fullDescription: 'Hail is a tool for Android that allows users to “freeze” apps—that is, disable, hide, or suspend them—when they are not needed. By doing so, it helps in reducing memory (RAM) consumption and conserving battery life. The apps that are frozen can be reverted (“unfrozen”) when needed.\n\n“Hiding” means the app will not appear in the launcher or in the installed apps list (but can be unhidden). “Disabling” removes it from the launcher (but can be enabled again). “Suspending” (on supported Android versions) shows the icon in grayscale and prevents background activity, popping up a dialog if the user tries to open it.',
        size: '3.3 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.mediafire.com/file/e7y23htnzsoygf8/Hail_1.8.1.zip/file',
        isModified: false,
        screenshots: ['https://i.ytimg.com/vi/fI0D6c4VNZA/maxresdefault.jpg', 'https://droidwin.com/wp-content/uploads/2024/09/hail-app.jpg', 'https://f-droid.org/repo/com.aistra.hail/en-US/phoneScreenshots/3.png'],
        features: ['Freeze / unfreeze apps (disable, hide, suspend)', 'GrapheneOS Discussion Forum', 'Support for different working modes: Device Owner, Root, Shizuku, Dhizuku', 'Revert changes (unfreeze) easily when needed', 'Hide apps (so they don’t appear in launcher or app list)', 'Suspend apps (icon turns grayscale; background and notifications are blocked) on supported versions', 'Works without root for many features (via Shizuku / Dhizuku)', 'GrapheneOS Discussion Forum', 'Free and open source (GPL-3.0)']
    },
    {
        id: 1760670417792,
        name: ' APK Editor Pro',
        version: '1.6.12',
        category: 'Utilities',
        icon: 'https://img.utdstc.com/icon/ca3/0e4/ca30e4b2f2d983f2f1b1436d64bca9be55e5b8f2a900b09bdee5e446b34bfd8c:200',
        description: 'This is the very best application to edit your APK files easily. With this app, you can explore the contents of an APK file',
        fullDescription: 'APK Editor Pro is a professional Android application designed for modifying APK files directly on your device. It enables users to edit app resources, change layouts, replace icons, modify strings, and even remove ads or permissions. The tool supports both full APK editing and simple file replacement, making it suitable for both beginners and advanced users. With an intuitive interface and robust functionality, it’s one of the best tools for customizing Android apps according to your needs.',
        size: '5.31',
        downloadLink: 'https://www.mediafire.com/file/f1iczua6mblucyv/APK_Editor_Pro.ver.1.6.12.build.70.rar/file',
        originalDownloadLink: 'https://apk-editor.com/',
        isModified: true,
        screenshots: ['https://apk-editor.com/wp-content/uploads/2025/05/APK-Editor-for-Pro-Mod-1024x550.webp', 'https://www.latestmodapks.com/wp-content/uploads/2022/08/apk-editor5.webp', 'https://imag.malavida.com/mvimgbig/download-fs/apk-editor-20899-1.jpg'],
        features: ['Edit APK files easily and quickly.', 'Modify app resources, layouts, and images.', 'Remove unwanted ads and permissions.', 'Replace app icons and backgrounds.', 'Support for full APK rebuild or simple edit modes.', 'User-friendly interface.', 'Backup and restore feature for safety.', 'Works without requiring root (for most edits).']
    },
    {
        id: 1760670709239,
        name: ' App Cloner VIP',
        version: '2.1.1',
        category: 'Utilities',
        icon: 'https://media.infosec.exchange/infosec.exchange/media_attachments/files/109/483/691/260/285/976/original/c7166899de75f0e4.png',
        description: 'App Cloner is a popular third-party app cloning tool to create multiple instances of an app for use with different accounts and logins',
        fullDescription: 'App Cloner (VIP / Premium) lets you duplicate Android apps and modify cloned instances with options such as changing the app name and icon, removing permissions, disabling auto-start, spoofing identifiers, adding privacy options (hide Android ID, Wi-Fi/Bluetooth MAC), password-protecting clones, and more. It supports both simple cloning and advanced modifications via add-ons; some advanced mods and large-scale cloning limits are unlocked in the VIP/Premium edition.',
        size: '21.3',
        downloadLink: 'https://www.mediafire.com/file/n8o49lrwo38d0gk/App_Cloner_VIP_%255BMod_By_ANON%255D_2.1.1.rar/file',
        originalDownloadLink: 'https://appcloner.app/',
        isModified: true,
        screenshots: ['https://play-lh.googleusercontent.com/RjZbsmh22gbDGBsGPqVE16EkOX8h0wVJUm81lsJ79NA8AtSlPbzJv0U8rMH2e7oHmyE=w526-h296-rw', 'https://liteapks.com/wp-content/uploads/2022/05/app-cloner-1-e1653727930941.png', 'https://images.wondershare.com/drfone/article/2024/02/android-clone-apps-10.jpg'],
        features: ['Create multiple independent clones of installed apps.', 'appcloner.app', 'Customize clone name, icon, and package signature.', 'APKMirror', 'Remove or limit permissions, disable auto-start and background services.', 'appcloner.app', 'Privacy & spoofing options (hide/switch Android ID, spoof MAC, fake GPS).', 'App Cloner', 'Password-protect clones and enable incognito/stealth modes.', 'appcloner.app', 'VIP/Premium unlocks advanced mods, more cloning limits, and add-ons.', 'LITEAPKS', '+1', 'Note: compatibility differs by target app — some apps (banking, DRM apps, Google Pay, etc.) may refuse to run under clones or require additional steps.']
    },
    {
        id: 1760670886353,
        name: 'NP Manager',
        version: '3.1.25',
        category: 'Utilities',
        icon: 'https://www.farsroid.com/wp-content/uploads/NP-Manager-Logo.png',
        description: 'Easily manage your Android media with NP Manager\nSimilar to MTManager',
        fullDescription: 'NP Manager is a multifunctional Android application designed for developers and advanced users who need to analyze and modify APK files. It integrates file management, decompiling, recompiling, signing, text editing, and patching features in one interface. With NP Manager, you can explore APK structures, edit Smali and XML files, change app permissions, remove ads, modify code, and rebuild applications. It’s particularly useful for those who work on app localization, debugging, or customization. The app supports both root and non-root modes, offering flexibility and control over Android packages.',
        size: '43.3',
        downloadLink: 'https://www.mediafire.com/file/53kwfu3oy13g50e/NP_Manager_3.1.25.rar/file',
        isModified: false,
        screenshots: ['https://mt-manager.net/wp-content/uploads/2025/03/Np-Manager-1.webp', 'https://media.licdn.com/dms/image/v2/D4D12AQHDldvcBNy1eQ/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1712047272179?e=2147483647&v=beta&t=xetqVlYawDLP2rgf_YkWb_TtvL-HUNPFQyrKnhrSLn0', 'https://media.licdn.com/dms/image/v2/D4D12AQHDldvcBNy1eQ/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1712047272179?e=2147483647&v=beta&t=xetqVlYawDLP2rgf_YkWb_TtvL-HUNPFQyrKnhrSLn0'],
        features: ['Full-featured file manager with APK editing tools.', 'Decompile, recompile, and sign APK files easily.', 'Built-in Smali, XML, and text editor.', 'Patch apps and modify internal code.', 'Remove ads and unnecessary permissions.', 'Supports both root and non-root environments.', 'Customize and rebuild Android applications.', 'Fast and lightweight performance.']
    },
    {
        id: 1760671090904,
        name: 'ZArchiver Pro',
        version: '1.0.8',
        category: 'Utilities',
        icon: 'https://appteka.store/get/e2Wp1PQuDKBDXQnr3xx9xFbvp_n8xmKoUUVKra4uCno41GZQ-konjdEB7zxrPUYmMNd5Nn6lB4mKl8BZNr2HRokU-I4=/51b296dd65d989fbd9b5c15b5b86b041c9ae3d49.png',
        description: 'ZArchiver - is a program for archive management (including managing of application backups in archives)',
        fullDescription: 'ZArchiver Pro is an advanced Android application designed for handling compressed archives and file management. It supports a wide range of formats such as ZIP, RAR, 7z, TAR, ISO, and more. With its clean interface and powerful engine, users can create new archives, extract existing ones, add passwords, encrypt files, and manage multi-part archives directly from their device. The Pro version enhances performance, adds premium features such as dark mode themes, better compression speed, and full UTF-8 file name support. It’s an essential app for users who frequently manage compressed files on mobile devices.',
        size: '4.84',
        downloadLink: 'https://www.mediafire.com/file/kkxv00vgfg0au2a/ZArchiver_Pro.rar/file',
        isModified: false,
        screenshots: ['https://zarchiverr.pro/wp-content/uploads/2024/12/ZArchiver-Donate-Latest-v1.0.10-for-Android-2025.webp', 'https://www.zarchiver.pro/wp-content/uploads/2021/07/zarchiver-apk.jpg', 'https://img.utdstc.com/screen/227/2c1/2272c114a54839b3d40b4b497bc02be04900fd9cb0b3be5ea860fb500ae206ef:600'],
        features: ['Create and extract archives in multiple formats (ZIP, RAR, 7z, TAR, etc.).', 'Compress files with password protection and encryption.', 'View and edit compressed file contents without extracting.', 'Support for multi-part and split archives.', 'Simple and modern user interface.', 'UTF-8 encoding support for non-Latin filenames.', 'Fast compression and decompression performance.', 'Full dark/light theme customization (Pro).', 'No ads and improved stability in Pro version.']
    }
];

// ===== FRP Tools Data =====
const frpTools = [
    {
        id: 1760951936012,
        name: 'TFT Unlock Tool',
        version: '6.2.1.1',
        category: 'Universal',
        icon: 'https://iranxda.ir/wp-content/uploads/2022/08/tft-unlocker-cracked.webp',
        description: 'Here we will know what TFT tools is and how it works. TFT is the name of a software that can be installed on a computer or laptop. With its help, you can repair mobile OS. It is very easy to use. You can also use the tool for free but with some limits.',
        fullDescription: 'To use all its features, you will have to purchase it. But if you have one or two mobiles, then you can very easily use it for free. Or many of its free versions are available on the Internet. There are many versions of TFT Tool. And from here you will be able to download the Latest Version.\n\nWhat is the minimum system requirement to run this software tools? This has been explained in details here. There are very few requirements to use TFT Unlock Tool Crack. Below we have explained in detail that this software can be used at least during retirement. Its details are available below.\n\nWindows PC (Windows 7 or later)\n1GB of available disk space\nUSB ports for device connection\nAt least 4GB of RAM\n\nCompatibility with Operating Systems\nTFT Tool can be installed on the following operating systems:\n\nWindows 7, 8, 10, and 11\nMac OS (with emulator)\nLinux (with emulator)\n\n\nInstallation password: TFT',
        size: '310 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://www.mediafire.com/file/5xxyloukdhhdqof/TFTUnlock+Tool+V6.2.1.1.zip/file',
        isModified: false,
        screenshots: ['https://i.ytimg.com/vi/MQPHKfumOOc/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLC8rzhNfuRzQ7Lf2G05H2uPAnxM6Q', 'https://media.licdn.com/dms/image/sync/v2/D4D27AQFlskt6L_e7KA/articleshare-shrink_800/articleshare-shrink_800/0/1746558211000?e=2147483647&v=beta&t=GmhuVm0t604xnckNemaWa0lOnRhpLtjufzO_RqMOeyU', 'https://pbs.twimg.com/media/GLltenJbkAAp1LV.jpg'],
        features: ['Unlocking and Security Removal', 'Remove screen locks (pattern, PIN, password, or fingerprint).', 'Bypass FRP (Factory Reset Protection) after a factory reset.', 'Unlock OEM and Bootloader on supported devices.', 'Repair and Maintenance Tools', 'Perform a full format or factory reset.', 'Flash firmware (ROM) or install the official system software.', 'Repair network or IMEI on supported devices.', 'Recover bricked or dead devices (Unbrick / Recovery Mode).', 'Broad Device and Chipset Support', 'Supports devices powered by Qualcomm, MediaTek, Spreadtrum (UniSoc), and Kirin chipsets.', 'Read detailed device information (model, CPU, Android version, lock status).', 'Professional Utilities', 'Built-in account management system (login / activation).', 'Ability to work with multiple devices simultaneously.', 'Option to back up user data before performing operations.', 'Interface and Usability', 'Simple, user-friendly interface for Windows PCs.', 'Does not require advanced technical skills.', 'Regular updates to support new devices and security patches.']
    }
];

// ===== FRP Applications Data =====
const frpApps = [
    {
        id: 1760868637661,
        name: 'Settings',
        version: '1.0',
        category: 'Universal',
        icon: 'fa-solid fa-gear',
        description: 'Open phone settings',
        size: '0 MB',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.android.settings/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760868987987,
        name: 'Galaxy Store',
        version: '1.0',
        category: 'Samsung',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Galaxy_store_logo.png',
        description: 'Open Galaxy Store',
        size: '0 MB',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.sec.android.app.samsungapps/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760869067510,
        name: ' Google Search app',
        version: '1.0',
        category: 'Universal',
        icon: 'https://frpbypass.romstage.com/wp-content/uploads/2022/02/search-min-150x150.png',
        description: 'Open Google search engine',
        size: '0 MB',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.google.android.googlequicksearchbox/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760869141205,
        name: 'Set Lock Screen',
        version: '1.0',
        category: 'Universal',
        icon: 'https://frpbypass.romstage.com/wp-content/uploads/2024/09/image.png',
        description: 'Screen lock settings',
        size: '0 MB',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.google.android.gms/#Intent;scheme=promote_smartlock_scheme;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760869804354,
        name: 'FRP Bypass apk',
        version: '1.0',
        category: 'Universal',
        icon: 'https://cdn-icons-png.flaticon.com/512/8156/8156962.png',
        description: 'Application to add a skip account to Android devices',
        size: '1.17 MB',
        downloadLink: '#',
        originalDownloadLink: 'https://frpbypass.romstage.com/frp_bypass/',
        isModified: false,
        linkType: 'download'
    },
    {
        id: 1760869897074,
        name: 'Motorola',
        version: '1.0',
        category: 'Moto',
        icon: 'https://frpbypass.romstage.com/wp-content/uploads/2022/11/unnamed-150x150.png',
        description: 'Open device settings Motorola',
        size: '0',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.motorola.moto/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760869974405,
        name: 'Moto Secure',
        version: '1.0',
        category: 'Moto',
        icon: 'https://frpbypass.romstage.com/wp-content/uploads/2025/02/Moto-Secure-cpunlock.com_-150x150-1.png',
        description: 'Open your security application Motorola',
        size: '0',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.motorola.securityhub/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760870041088,
        name: 'Open Google Assistant',
        version: '1.0',
        category: 'Universal',
        icon: 'https://frpbypass.romstage.com/wp-content/uploads/2022/11/unnamed-2-150x150.png',
        description: 'Open Google Assistant for Android devices',
        size: '0',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.google.android.apps.googleassistant/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760870094155,
        name: 'Open Samsung My Files',
        version: '1.0',
        category: 'Samsung',
        icon: 'https://frpbypass.romstage.com/wp-content/uploads/2023/09/Samsun-my-files-150x150.webp',
        description: 'Open Samsung\'s Files app',
        size: '0',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.sec.android.app.myfiles/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760870234652,
        name: 'Open Mi File Manager',
        version: '1.0',
        category: 'Xiaomi',
        icon: 'https://frpbypass.romstage.com/wp-content/uploads/2022/11/mi-file-menager-150x150.png',
        description: 'Open the Files application for Xiaomi devices',
        size: '0',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.mi.android.globalFileexplorer/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760870931873,
        name: 'Open YouTube',
        version: '1.0',
        category: 'Universal',
        icon: 'https://frpbypass.romstage.com/wp-content/uploads/2022/01/image.png',
        description: 'Open the YouTube application for Android devices',
        size: '0',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.google.android.youtube/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    },
    {
        id: 1760870974710,
        name: 'Open Activity Manager',
        version: '1.0',
        category: 'general',
        icon: 'https://frpbypass.romstage.com/wp-content/uploads/2024/08/activity-manager.png',
        description: 'No description provided',
        size: '5 MB',
        downloadLink: '#',
        originalDownloadLink: 'intent://com.activitymanager/#Intent;scheme=android-app;end',
        isModified: false,
        linkType: 'direct'
    }
];